name: C/C++ CI

on: 
  push:
    branches:
    - master
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make CGI scripts of master
      run: make

    - name: Upload compilation result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: www-binaries
        path: www/cgi-bin/

  deploy:
    name: Deploy to webserver
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: www-binaries
          path: www/cgi-bin/
      - name: Push to ftp server
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
          # FTP server name (you may need to specify a port)
          ftp_server: www.florianhofer.it
          # FTP account username
          ftp_username: ${{ secrets.WWW-FTPU }}
          # FTP account password
          ftp_password: ${{ secrets.WWW-FTPP }}
          # The local folder to copy, defaults to root project folder
          local_dir: www/
          # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
          remote_dir: www.florianhofer.it/
